[tool.poetry]
name = "crawler"
version = "0.1.0"
description = ""
authors = ["Jaeyoung Park <alska1039@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
